apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app}
  namespace: ${namespace}
  labels:
    app: ${app}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${app}
  template:
    metadata:
      labels:
        app: ${app}
    spec:
      containers:
      - name: ${app}
        image: ${image}
        resources:
          requests:
            cpu: ${cpu}
            memory: ${memory}
        ports:
        - containerPort: 80
