apiVersion: v1
kind: Service
metadata:
  name: ${parameters.app}
  namespace: ${parameters.Namespace}
spec:
  type: LoadBalancer
  selector:
    app: ${parameters.app}
  ports:
    - port: 80
      targetPort: 80
