# apiVersion: v1
# kind: Service
# metadata:
#   name: ${parameters.app}
#   namespace: ${parameters.namespace}
# spec:
#   type: LoadBalancer
#   selector:
#     app: ${parameters.app}
#   ports:
#     - port: 80
#       targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#     - port: 80
#       targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: ${parameters_app}
  namespace: ${parameters_namespace}
spec:
  type: LoadBalancer
  selector:
    app: ${parameters_app}
  ports:
    - port: 80
      targetPort: 80
