# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - ../../base

# #configMapGenerator:
#  # - name: app-params
#   #  files:
#    #   - parameter.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${parameters.namespace}

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml


